/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#0D2F30',
          secondary: '#A5815E',
        },
        'brand-primary': '#0D2F30',
        'brand-secondary': '#A5815E',
        tertiary: '#001a1b',
        'primary-fixed': '#c7e9ea',
        'surface-tint': '#446465',
        'tertiary-container': '#003032',
        outline: '#717878',
        'primary-container': '#0d2f30',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdd2aa',
        'on-primary-container': '#779798',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002021',
        'on-tertiary-container': '#6c999b',
        'tertiary-fixed': '#bcebed',
        'on-primary-fixed-variant': '#2c4c4d',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#1e4e50',
        'inverse-on-surface': '#eaf1ff',
        'error-container': '#ffdad6',
        'on-background': '#0d1c2e',
        'on-secondary-fixed-variant': '#5d4123',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002021',
        'primary-fixed-dim': '#abcdce',
        error: '#ba1a1a',
        'inverse-primary': '#abcdce',
        'secondary-fixed-dim': '#e8bf98',
        'on-surface': '#0d1c2e',
        'on-secondary-fixed': '#2c1600',
        'tertiary-fixed-dim': '#a0cfd1',
        'surface-container-highest': '#d5e3fc',
        'outline-variant': '#c1c8c8',
        'surface-container': '#e6eeff',
        'on-surface-variant': '#414848',
        surface: '#f8f9ff',
        'inverse-surface': '#233144',
        'surface-dim': '#ccdbf3',
        background: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-container-low': '#eff4ff',
        secondary: '#785838',
        primary: '#00191a',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffdcbd',
        'surface-variant': '#d5e3fc',
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#785939',
        success: {
          text: '#065F46',
          bg: '#ECFDF5',
          border: '#A7F3D0',
        },
        warning: {
          text: '#92400E',
          bg: '#FEF3C7',
          border: '#FDE68A',
        },
        danger: {
          text: '#991B1B',
          bg: '#FEF2F2',
          border: '#FECACA',
        },
        hifz: {
          text: '#0D2F30',
          bg: '#E6F0F0',
          border: '#B2D1D2',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        arabic: ['Amiri', 'serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'title-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      width: {
        sidebar: '260px',
        'sidebar-collapsed': '72px',
      },
      boxShadow: {
        card: '0px 1px 3px rgba(13, 47, 48, 0.04), 0px 1px 2px rgba(13, 47, 48, 0.02)',
        popover:
          '0px 4px 6px -1px rgba(13, 47, 48, 0.07), 0px 2px 4px -2px rgba(13, 47, 48, 0.05)',
        modal:
          '0px 20px 25px -5px rgba(13, 47, 48, 0.1), 0px 8px 10px -6px rgba(13, 47, 48, 0.06)',
      },
    },
  },
  plugins: [],
};
